export const taskTypes = [
	'Product Review Analysis',
	'Customer Satisfaction Survey',
	'Market Research Evaluation',
	'Social Media Engagement Audit',
	'Competitor Pricing Assessment',
	'User Feedback Categorization',
	'Ad Performance Tracking',
	'SEO Keyword Optimization',
	'Brand Perception Study',
	'Customer Journey Mapping',
	'Online Reputation Monitoring',
	'Website Usability Testing',
	'Influencer Campaign Effectiveness',
	'Consumer Trend Analysis',
	'Content Strategy Evaluation',
	'Product Feature Prioritization',
	'Service Quality Benchmarking',
	'Purchase Behavior Analysis',
	'Social Listening Insights',
	'Market Demand Forecasting',
	'Customer Support Audit',
	'Brand Awareness Measurement',
	'UX Design Feedback Collection',
	'Mobile App Usability Test',
	'Marketing Funnel Analysis',
	'User Experience Satisfaction',
	'Ad Copy Effectiveness Test',
	'Retail Store Experience Review',
	'Digital Ad Targeting Analysis',
	'Content Personalization Study',
	'Video Ad Engagement Metrics',
	'Voice of Customer Analysis',
	'E-commerce Cart Abandonment Review',
	'Email Campaign Conversion Tracking',
	'Subscription Churn Rate Analysis',
	'Promotional Campaign Effectiveness',
	'Consumer Trust Score Evaluation',
	'Lead Generation Effectiveness',
	'Social Media Content Performance',
	'Customer Loyalty Program Review',
];

export const locales = [
	'English: United States',
	'Spanish: Mexico',
	'German: Germany',
	'French: France',
	'Italian: Italy',
	'Japanese: Japan',
	'Chinese: China',
	'Portuguese: Brazil',
	'Russian: Russia',
	'Korean: South Korea',
	'Dutch: Netherlands',
	'Arabic: Saudi Arabia',
	'Turkish: Turkey',
];
